window.BASEBALL_CARD_PLAYERS = [
  {
    id: 1,
    name: "Mickey Wagner",
    contact: 82,
    power: 38,
    discipline: 78,
    speed: 92,
    trait: "Table Setter",
    traitText: "+10 single chance with empty bases"
  },
  {
    id: 2,
    name: "Chuck Wagner",
    contact: 76,
    power: 62,
    discipline: 70,
    speed: 68,
    trait: "Rally Bat",
    traitText: "+12 double chance with runners on"
  },
  {
    id: 3,
    name: "Kayleigh Wagner",
    contact: 68,
    power: 92,
    discipline: 64,
    speed: 42,
    trait: "Moonshot",
    traitText: "+15 HR chance with 2+ runners on"
  },
  {
    id: 4,
    name: "Kyle Wagner",
    contact: 94,
    power: 40,
    discipline: 88,
    speed: 60,
    trait: "Bat Control",
    traitText: "+15 contact outcomes, fewer strikeouts"
  },
  {
    id: 5,
    name: "Cookie Wagner",
    contact: 70,
    power: 36,
    discipline: 66,
    speed: 98,
    trait: "Base Thief",
    traitText: "+20 extra base chance on hits"
  },
  {
    id: 6,
    name: "Kasey Wagner",
    contact: 78,
    power: 74,
    discipline: 72,
    speed: 70,
    trait: "Balanced",
    traitText: "+5 to all outcomes"
  },
  {
    id: 7,
    name: "Sam Wagner",
    contact: 72,
    power: 58,
    discipline: 95,
    speed: 52,
    trait: "Eagle Eye",
    traitText: "+20 walk chance"
  },
  {
    id: 8,
    name: "John Wagner",
    contact: 64,
    power: 96,
    discipline: 60,
    speed: 38,
    trait: "First Pitch Killer",
    traitText: "+20 HR chance first pitch"
  },
  {
    id: 9,
    name: "Mitch Wagner",
    contact: 88,
    power: 60,
    discipline: 74,
    speed: 66,
    trait: "Laser Contact",
    traitText: "+15 double chance"
  },
  {
    id: 10,
    name: "Gu Wagner",
    contact: 80,
    power: 78,
    discipline: 70,
    speed: 58,
    trait: "Clutch Gene",
    traitText: "+15 all stats in late innings"
  },
  {
    id: 11,
    name: "Froggie Wagner",
    contact: 75,
    power: 65,
    discipline: 76,
    speed: 72,
    trait: "Scrapper",
    traitText: "+10 on all 2-strike counts"
  },
  {
    id: 12,
    name: "Casey Wagner",
    contact: 84,
    power: 54,
    discipline: 82,
    speed: 60,
    trait: "Inside-Out Swing",
    traitText: "+15 hit chance vs tough pitchers"
  },
  {
    id: 13,
    name: "Noah Wagner",
    contact: 66,
    power: 88,
    discipline: 58,
    speed: 50,
    trait: "Heat Seeker",
    traitText: "+20 power vs fastballs"
  },
  {
    id: 14,
    name: "Mike Wagner",
    contact: 85,
    power: 80,
    discipline: 68,
    speed: 78,
    trait: "Breakout",
    traitText: "Random +20 boost each at-bat"
  },
  {
    id: 15,
    name: "Joey Wagner",
    contact: 82,
    power: 70,
    discipline: 90,
    speed: 48,
    trait: "Game Sense",
    traitText: "Reduces strikeouts significantly"
  },
  {
    id: 16,
    name: "UD Wagner",
    contact: 86,
    power: 72,
    discipline: 74,
    speed: 64,
    trait: "Spray Hitter",
    traitText: "+15 doubles, +5 singles"
  },
  {
    id: 17,
    name: "Mitch Buzard",
    contact: 78,
    power: 82,
    discipline: 66,
    speed: 52,
    trait: "Cold Start",
    traitText: "+25 first at-bat outcome"
  },
  {
    id: 18,
    name: "Dom DaMascio",
    contact: 68,
    power: 42,
    discipline: 60,
    speed: 96,
    trait: "Disruptor",
    traitText: "Forces errors / extends plays"
  },
  {
    id: 19,
    name: "Mike Popovitch",
    contact: 74,
    power: 88,
    discipline: 62,
    speed: 90,
    trait: "Dual Threat",
    traitText: "+10 HR and +10 extra base chance"
  },
  {
    id: 20,
    name: "RC Wagner",
    contact: 90,
    power: 55,
    discipline: 84,
    speed: 58,
    trait: "Execution",
    traitText: "+20 with runners in scoring position"
  },
  {
    id: 21,
    name: "Pat Wagner",
    contact: 70,
    power: 48,
    discipline: 98,
    speed: 50,
    trait: "On Base",
    traitText: "Massively increased walk rate"
  },
  {
    id: 22,
    name: "Jared Fisher",
    contact: 72,
    power: 90,
    discipline: 60,
    speed: 55,
    trait: "Momentum",
    traitText: "HRs boost next batter"
  },
  {
    id: 23,
    name: "Tyler Vieria",
    contact: 84,
    power: 82,
    discipline: 76,
    speed: 60,
    trait: "9th Inning",
    traitText: "+25 stats in final inning"
  },
  {
    id: 24,
    name: "Chris Rohan",
    contact: 88,
    power: 52,
    discipline: 78,
    speed: 88,
    trait: "Pressure",
    traitText: "Forces defensive mistakes"
  },
  {
    id: 25,
    name: "Bob Buettner",
    contact: 55,
    power: 99,
    discipline: 50,
    speed: 40,
    trait: "All or Nothing",
    traitText: "HR or strikeout bias"
  },
  {
    id: 26,
    name: "Ben Prylinski",
    contact: 92,
    power: 60,
    discipline: 85,
    speed: 62,
    trait: "Reliable",
    traitText: "Reduces variance of outcomes"
  },
  {
    id: 27,
    name: "John Dougherty",
    contact: 70,
    power: 92,
    discipline: 64,
    speed: 52,
    trait: "Velocity Hunter",
    traitText: "+20 vs high velocity"
  },
  {
    id: 28,
    name: "Anthony Blakelee",
    contact: 86,
    power: 30,
    discipline: 82,
    speed: 90,
    trait: "Manufacture Runs",
    traitText: "+20 singles and advancement"
  },
  {
    id: 29,
    name: "Jake VanScyoc",
    contact: 78,
    power: 66,
    discipline: 94,
    speed: 58,
    trait: "Mind Games",
    traitText: "Boosts favorable counts"
  },
  {
    id: 30,
    name: "Anthony Blaszczyk",
    contact: 88,
    power: 88,
    discipline: 80,
    speed: 88,
    trait: "Superstar",
    traitText: "+10 all stats permanently"
  }
];
window.BASEBALL_CARD_PLAYERS = [
  {
    id: 1,
    tier: "Legendary",
    name: "Pablo Sanchez",
    batPower: 100,
    batContact: 63,
    power: 100,
    contact: 63,
    hitting: 99,
    speed: 80,
    fielding: 99,
    overall: 99,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 2,
    tier: "Epic",
    name: "Kiesha Phillips",
    batPower: 87,
    batContact: 67,
    power: 87,
    contact: 67,
    hitting: 80,
    speed: 81,
    fielding: 83,
    overall: 87,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 3,
    tier: "Legendary",
    name: "Pete Wheeler",
    batPower: 80,
    batContact: 50,
    power: 80,
    contact: 50,
    hitting: 69,
    speed: 99,
    fielding: 82,
    overall: 86,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 4,
    tier: "Epic",
    name: "Dante Robinson",
    batPower: 50,
    batContact: 39,
    power: 50,
    contact: 39,
    hitting: 55,
    speed: 87,
    fielding: 85,
    overall: 80,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 5,
    tier: "Epic",
    name: "Achmed Khan",
    batPower: 95,
    batContact: 84,
    power: 95,
    contact: 84,
    hitting: 93,
    speed: 65,
    fielding: 63,
    overall: 80,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 6,
    tier: "Epic",
    name: "Stephanie Morgan",
    batPower: 40,
    batContact: 72,
    power: 40,
    contact: 72,
    hitting: 66,
    speed: 67,
    fielding: 81,
    overall: 76,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 7,
    tier: "Rare",
    name: "Lisa Crocket",
    batPower: 67,
    batContact: 16,
    power: 67,
    contact: 16,
    hitting: 65,
    speed: 77,
    fielding: 69,
    overall: 76,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 8,
    tier: "Rare",
    name: "Amir Khan",
    batPower: 73,
    batContact: 64,
    power: 73,
    contact: 64,
    hitting: 89,
    speed: 55,
    fielding: 43,
    overall: 75,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 9,
    tier: "Rare",
    name: "Dmitri Petrovich",
    batPower: 78,
    batContact: 57,
    power: 78,
    contact: 57,
    hitting: 77,
    speed: 65,
    fielding: 52,
    overall: 75,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 10,
    tier: "Rare",
    name: "Tony Delvecchio",
    batPower: 74,
    batContact: 56,
    power: 74,
    contact: 56,
    hitting: 77,
    speed: 52,
    fielding: 84,
    overall: 74,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 11,
    tier: "Rare",
    name: "Sally Dobbs",
    batPower: 94,
    batContact: 1,
    power: 94,
    contact: 1,
    hitting: 70,
    speed: 66,
    fielding: 75,
    overall: 74,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 12,
    tier: "Uncommon",
    name: "Reese Worthington",
    batPower: 46,
    batContact: 25,
    power: 46,
    contact: 25,
    hitting: 55,
    speed: 71,
    fielding: 79,
    overall: 74,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 13,
    tier: "Rare",
    name: "Vicki Kawaguchi",
    batPower: 25,
    batContact: 25,
    power: 25,
    contact: 25,
    hitting: 48,
    speed: 83,
    fielding: 85,
    overall: 74,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 14,
    tier: "Uncommon",
    name: "Jocinda Smith",
    batPower: 54,
    batContact: 100,
    power: 54,
    contact: 100,
    hitting: 81,
    speed: 43,
    fielding: 76,
    overall: 73,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 15,
    tier: "Uncommon",
    name: "Annie Frazier",
    batPower: 38,
    batContact: 96,
    power: 38,
    contact: 96,
    hitting: 61,
    speed: 73,
    fielding: 59,
    overall: 72,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 16,
    tier: "Uncommon",
    name: "Ernie Steele",
    batPower: 62,
    batContact: 36,
    power: 62,
    contact: 36,
    hitting: 68,
    speed: 56,
    fielding: 82,
    overall: 72,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 17,
    tier: "Uncommon",
    name: "Mikey Thomas",
    batPower: 90,
    batContact: 81,
    power: 90,
    contact: 81,
    hitting: 94,
    speed: 30,
    fielding: 70,
    overall: 70,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 18,
    tier: "Uncommon",
    name: "Luanne Lui",
    batPower: 18,
    batContact: 77,
    power: 18,
    contact: 77,
    hitting: 38,
    speed: 95,
    fielding: 53,
    overall: 70,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 19,
    tier: "Uncommon",
    name: "Jorge Garcia",
    batPower: 82,
    batContact: 58,
    power: 82,
    contact: 58,
    hitting: 69,
    speed: 55,
    fielding: 66,
    overall: 68,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 20,
    tier: "Common",
    name: "Maria Luna",
    batPower: 67,
    batContact: 45,
    power: 67,
    contact: 45,
    hitting: 76,
    speed: 59,
    fielding: 57,
    overall: 68,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 21,
    tier: "Common",
    name: "Ronny Dobbs",
    batPower: 86,
    batContact: 24,
    power: 86,
    contact: 24,
    hitting: 71,
    speed: 51,
    fielding: 60,
    overall: 67,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 22,
    tier: "Common",
    name: "Kenny Kawaguchi",
    batPower: 19,
    batContact: 49,
    power: 19,
    contact: 49,
    hitting: 50,
    speed: 69,
    fielding: 57,
    overall: 67,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 23,
    tier: "Common",
    name: "Ashley Webber",
    batPower: 34,
    batContact: 62,
    power: 34,
    contact: 62,
    hitting: 62,
    speed: 61,
    fielding: 53,
    overall: 66,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 24,
    tier: "Common",
    name: "Sidney Webber",
    batPower: 34,
    batContact: 62,
    power: 34,
    contact: 62,
    hitting: 62,
    speed: 61,
    fielding: 53,
    overall: 66,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 25,
    tier: "Common",
    name: "Gretchen Hasselhoff",
    batPower: 41,
    batContact: 22,
    power: 41,
    contact: 22,
    hitting: 40,
    speed: 75,
    fielding: 53,
    overall: 64,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 26,
    tier: "Common",
    name: "Billy Jean Blackwood",
    batPower: 29,
    batContact: 95,
    power: 29,
    contact: 95,
    hitting: 61,
    speed: 54,
    fielding: 61,
    overall: 64,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 27,
    tier: "Common",
    name: "Kimmy Eckman",
    batPower: 72,
    batContact: 42,
    power: 72,
    contact: 42,
    hitting: 69,
    speed: 33,
    fielding: 58,
    overall: 58,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 28,
    tier: "Common",
    name: "Angela Delvecchio",
    batPower: 89,
    batContact: 40,
    power: 89,
    contact: 40,
    hitting: 85,
    speed: 33,
    fielding: 32,
    overall: 58,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 29,
    tier: "Common",
    name: "Marky Dubois",
    batPower: 57,
    batContact: 49,
    power: 57,
    contact: 49,
    hitting: 62,
    speed: 36,
    fielding: 72,
    overall: 57,
    trait: "Balanced",
    traitText: "No special modifier yet"
  },
  {
    id: 30,
    tier: "Common",
    name: "Ricky Johnson",
    batPower: 25,
    batContact: 27,
    power: 25,
    contact: 27,
    hitting: 31,
    speed: 70,
    fielding: 53,
    overall: 57,
    trait: "Balanced",
    traitText: "No special modifier yet"
  }
];
